apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fortanix-test
  namespace: kube-system
spec:
  provider: fortanix-csi-provider
  parameters:
    dsmEndpoint: "<fortanix_dsm_endpoint>"
    dsmApikey: "<fortanix_dsm_apikey>"
    objects: |
      - secretName: "<secret_name>"

