apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: kube-system
spec:
  serviceAccountName: fortanix-csi-provider
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets"
      readOnly: true
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "fortanix-test"

